objc: true
clean: true
author: Skygear
author_url: https://skygear.io
github_url: https://github.com/SkygearIO/skygear-SDK-iOS/
github_file_prefix: https://github.com/SkygearIO/skygear-SDK-iOS/tree/master
umbrella_header: Pod/Classes/SKYKit.h
framework_root: .
module: SKYKit
skip_undocumented: true
hide_documentation_coverage: true
theme: fullwidth
sdk: iphonesimulator
exclude: "*_Private.h"
